version: '3.8'

services:
  finsy-app:
    # Jenkins sustituirá esto con la imagen que construya
    image: ${DOCKER_IMAGE_NAME:-finsy-app:latest}
    container_name: finsy-container
    ports:
      - "80:5000"
    environment:
      - DATABASE_URL=postgresql://user:password@${DB_INSTANCE_IP}:5432/finsydb
      - AWS_DEFAULT_REGION=us-east-1
    restart: always

networks:
  default:
    name: finsy-network