AWSTemplateFormatVersion: '2010-09-09'
Description: Despliegue Finsy - Intento Final Corregido

Resources:
  FinsyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      # Nombre unico para evitar conflictos globales
      BucketName: finsy-mya-deploy-final-2026

  FinsyInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      # ID limpio sin comillas para evitar el error de "Invalid id"
      ImageId: ami-0e2c8ccd4e1223c32 
      # RECUERDA: Verifica que en EC2 > Key Pairs el nombre sea MyA_Key
      KeyName: MyA_Key
      IamInstanceProfile: LabInstanceProfile
      Tags:
        - Key: Name
          Value: Finsy-Server-Prod
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          apt-get update -y
          apt-get install -y git docker.io
          systemctl start docker
          systemctl enable docker
          usermod -aG docker ubuntu
          
          # Clonar proyecto
          cd /home/ubuntu
          git clone https://github.com/Racoth505/MyA_ProyectoDevOps.git